server:
  port: 8760
spring:
  application:
    name: service-user
  cloud:
    #Consul配置
    consul:
      host: 10.19.154.66
      port: 8500
      discovery:
        register: true
        serviceName: ${spring.application.name}}
        port: ${server.port}
        hostname: ${spring.cloud.client.ip-address}
        enabled: true
#datasource 配置
  datasource:
    url: jdbc:mysql://192.168.2.131:3306/db_account?useSSL=false&serverTimezone=UTC
    username: root
    data-password: 123456
  jpa:
    show-sql: true