#server:
#  port: 8081
#  servlet:
#    context-path: /consul-feign-consumer
#spring:
#  application:
#    name: consul-feign-consumer
#  cloud:
#    consul:
#      host: 10.19.154.66
#      port: 8500
#      discovery:
#        #preferIpAddress: true
#       # health-check-path: ${server.servlet.context-path}/actuator/health
#        health-check-interval: 15s
#        serviceName: ${spring.application.name}
#      defaultContext: ${spring.application.name}