server:
  port: 8089
  servlet:
    context-path: /uaa
spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/ftl/
  security:
    oauth2:
      client:
        registration:
          weibo:
            provider: weibo
            client-id: 1970640892
            client-secret: 02e83978433140efaed8c95fa1b2600e
            authorization-grant-type: authorization_code
            redirect-uri: "http://3313m304b2.wicp.vip/uaa/login/oauth2/code/weibo"
            scope: follow_app_official_microblog
          wx:
            provider: wx
            client-id: 1970640892
            client-secret: 02e83978433140efaed8c95fa1b2600e
            authorization-grant-type: authorization_code
            redirect-uri: "http://3313m304b2.wicp.vip/login/oauth2/code/weibo"
            scope: follow_app_official_microblog
        provider:
          weibo:
            authorization-uri: https://api.weibo.com/oauth2/authorize
            token-uri: https://api.weibo.com/oauth2/access_token
            user-info-uri: https://api.weibo.com/2/users/show.json
          wx:
            authorization-uri: https://api.weibo.com/oauth2/authorize
            token-uri: https://api.weibo.com/oauth2/access_token
            user-info-uri: https://api.weibo.com/2/users/show.json