server:
  port: 8082
  servlet:
    context-path: /uaa
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            clientId: dsad
            clientSecret: dsa
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
  security:
    oauth2:
      client:
        registration:
          registration:
            weibo:
              provider: weibo
              client-id: aaaaa
              client-secret: bbbbb
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
              scope: follow_app_official_microblog
            wx:
              provider: wx
              client-id: wx87510450a64b4f2c
              client-secret: 813f02e5dbed65a407b782e9040ad938
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
              scope: snsapi_userinfo
        provider:
          weibo:
            authorization-uri: https://api.weibo.com/oauth2/authorize
            token-uri: https://api.weibo.com/oauth2/access_token
            user-info-uri: https://api.weibo.com/2/users/show.json
          wx:
            authorization-uri: https://open.weixin.qq.com/connect/oauth2/authorize
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-uri: https://api.weixin.qq.com/sns/userinfo