server:
  port: 9000
  servlet:
    context-path: /
    session:
      cookie:
        name: JSESSIONID_CLIENT2

security:
  oauth2:
    client:
      clientId: sampleClientId2
      clientSecret: secret
      accessTokenUri: http://localhost:9002/oauth/token
      logoutUri: http://localhost:9002/ssoLogout
      userAuthorizationUri: http://localhost:9002/oauth/authorize
    resource:
      userInfoUri: http://localhost:9002/user/me
spring:
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true

zuul:
  ignoredServices: '*'
  routes:
    resource-service:
      path: /resource/**
      url: http://localhost:9003/
      stripPrefix: true
      sensitiveHeaders: Cookie
    resource2-service:
      path: /resource2/**
      url: http://localhost:9004/
      stripPrefix: true
      sensitiveHeaders: Cookie