server:
  port: 9001

spring:
  http:
    converters:
      preferred-json-mapper: jackson
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.200:3306/oauth2_client_db?useSSL=false&useCharacterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

oauth2:
  client:
    client-id: client-a
    client-secret: client-a-secret
    redirect_uri: http://localhost:${server.port}/callback
    response_type: code
    scope: read_user_info
  server:
    host: http://localhost:8080
    authorize-url: ${oauth2.server.host}/oauth/authorize
    token-url: ${oauth2.server.host}/oauth/token
    check-token-url: ${oauth2.server.host}/oauth/check_token
