server:
  port: 990
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
      url: jdbc:mysql://192.168.2.200:3306/test?characterEncoding=utf8
      username: root
      password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
