server:
  port: 8762

spring:
  application:
    name: service-hi
  cloud:
    consul:
      host: 10.19.154.66
      port: 8500
      discovery:
        register: true
        serviceName: serfeign
        port: ${server.port}
        hostname: ${spring.cloud.client.ip-address}
        enabled: true