spring:
  application:
    name: gatway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        service-name: xxxx
        prefer-ip-address: true
    gateway:
      discovery:
        locator:
          enabled: true
      #配置路由节点  有哪些需要转发的 数组形式设置 配置文件用[] 或者- 表示数组
      routes:
        # This route rule used to forward request to activity server
        - id: activity-route  #每一个路由节点的ID
          uri: lb://activity  #路由转发的URL配置规则
          predicates:         #路由的谓词处理  有多种谓词处理
            - Path=/activity/**
          filters:            #路由用呢些处理
            - StripPrefix=1   #gatway使用哪些过滤的处理和过滤器的参数 这里的名称约定方式 前缀可以不写