#这里采用.yml文件方式设置属性，也可以使用.properties文件设置属性
#bootstrap最先加载 一些需要提处理放在bootstrap文件中进行处理
spring:
  profiles:
    active: dev
  cache:
    type: ehcache
    ehcache:
      config: dasd
#开启远程调试
  devtools:
    remote:
      #调试客户端和服务器之间的秘钥
      secret: 123456
  #配置Spring框架中使用的jackson的objectMapper的参数
  jackson:
    #可以自定义指定对应类型的名称去转换日期，可以设置日期格式 模式使用的是
    #SimpleDateFormat 然后传入格式进行转换
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
  mvc:
    #可以自定义指定对应类型的名称去转换日期，可以设置日期格式 模式使用的是
    date-format: yyyy/MM-dd HH:mm:ss
#配置web容器的参数 可以是 undertow
server:
  tomcat:
    max-threads: 10
    max-connections: 1000
#配置日志级别
logging:
  level:
    #appender
    root: info