#这里采用.yml文件方式设置属性，也可以使用.properties文件设置属性
#bootstrap最先加载 一些需要提处理放在bootstrap文件中进行处理
spring:
  profiles:
    active: dev
  cache:
    type: ehcache
    ehcache:
      config: dasd
#开启远程调试
  devtools:
    remote:
      #调试客户端和服务器之间的秘钥
      secret: 123456
server:
  tomcat:
    max-threads: 1000
    max-connections: 10000
  undertow:
    io-threads: 8
logging:
  level:
    #appender
    root: info